#!/bin/bash

mkdir -p ~/.ssh
chmod 700 ~/.ssh
ssh-keygen -t ed25519 -C "ugochukwu712@gmail.com" -f ~/.ssh/id_ed25519
cat ~/.ssh/id_ed25519.pub

ssh -T git@github.com
cd ~/ud120-projects
git remote set-url origin git@github.com:sodium-droid/ud120-projects.git

git config --global user.email "ugochukwu712@gmail.com"
git config --global user.name "Ugochukwu Okpoko"
